Tell Core Committers to include the list and not assume it's complete.
WordPress/props-bot-action pull request #45
Opened 2024-02-01 20:03 UTC by costdev

## What?
Tell Core Committers to make sure the usernames are _included_ in the props list, to avoid missing props for Trac contributions if the committer assumes its GitHub/Trac-complete.

## Why?
Props Bot currently handles interactions with a PR/related issues. Since it doesn't include Trac contributions yet, the props list it provides is likely incomplete.

2024-02-02 16:50 UTC, aaronjorbin commented on src/github.js
> +		"If you're a Core Committer, make sure these usernames are included in the props list when committing to `wordpress-develop` in SVN:\n" +
I worry this is getting too long.  What about:

`Core Committers: Use this line as a base for the props when committing in SVN`

It sets the expectation that the committer shouldn't blindly use the text in a concise manner

2024-02-02 17:29 UTC, desrosj requested changes
I share @aaronjorbin's concern about messaging being too long. I also prefer that `Props: ` be left in. It's helpful to already have the line formatted and then only needing to change the list members.

2024-02-05 15:46 UTC, desrosj commented on src/github.js
> +		"If you're a Core Committer, make sure these usernames are included in the props list when committing to `wordpress-develop` in SVN:\n" +
I like this suggestion. Could you update whenever you have a chance, @costdev?>

2024-02-05 21:03 UTC, costdev commented on src/github.js
> +		"If you're a Core Committer, make sure these usernames are included in the props list when committing to `wordpress-develop` in SVN:\n" +
Done 👍

2024-02-06 14:54 UTC, desrosj approved these changes

2024-02-06 15:02 UTC, desrosj commented
I also realized while reviewing that there's a `:` in the Props line. That should not be there.

2024-02-06 15:02 UTC, merged